### ISSUE TITLE
Suppress debug messages

### ISSUE THREAD

**Issue by mlagerberg** [Pixplicity/svg-android#20]
The library floods logcat with messages.

Desired functionality:
- Add a method `.setDebugEnabled(boolean)` to suppress trivial messages,
- Change some of the messages from level DEBUG to level VERBOSE (such as `Parsing complete in 9 ms.`),
- Log similar messages only once per session (such as `Unrecognized SVG command: clipPath`).

**Comment by filipc** [comment]
Most messing messages moved to VERBOSE log level.

**Comment by filipc** [comment]
Question about setDebugEnabled() method - do you mean to use external library like android-logger (https://github.com/noveogroup/android-logger) ?

Skipping similar messages forces collecting of logs. I think it is not good idea.

**Comment by pflammertsma** [comment]
No, we don't intend to include external libraries for logging as a part of Sharp. `setDebugEnabled(boolean)` simply suppresses `Log.v` and `Log.d` from being executed.

I believe it may be a better approach to offer a facility to set the log level.

**Comment by pflammertsma** [comment]
I agree that we should _not_ display messages once per session. An implementation is likely to cache (for instance to a bitmap), so it may be up to the implementation to suppress repeated messages.

In general, those scenarios where Sharp produces errors or warnings for otherwise valid SVGs should gradually be resolved with improvements to the library.
